import { existsSync, readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { spawn } from "node:child_process";
import { createInterface } from "node:readline/promises";
import { Writable } from "node:stream";
import { fileURLToPath } from "node:url";
import {
  ROOT,
  SECRET_KEYS,
  setup,
  configuration,
  readConfig,
  readSecrets,
  writeSecrets,
  privateWrite,
  api,
  ask,
  smoke,
  wrangler,
  deploy,
} from "./lib.mjs";
function options(args, allowed) {
  const values = {};
  for (let i = 0; i < args.length; i++) {
    const key = args[i].replace(/^--/, "");
    if (
      !args[i].startsWith("--") ||
      !allowed.includes(key) ||
      !args[i + 1] ||
      args[i + 1].startsWith("--")
    )
      throw new Error(
        "Expected " + allowed.map((k) => "--" + k + " VALUE").join(" "),
      );
    values[key] = args[++i];
  }
  return values;
}
async function hidden() {
  if (!process.stdin.isTTY) {
    const value = readFileSync(0, "utf8").trimEnd();
    if (!value) throw new Error("No secret supplied on stdin");
    return value;
  }
  const muted = new Writable({
    write(_chunk, _encoding, callback) {
      callback();
    },
  });
  const reader = createInterface({
    input: process.stdin,
    output: muted,
    terminal: true,
  });
  const controller = new AbortController();
  reader.on("SIGINT", () => controller.abort());
  process.stdout.write("Paste value (hidden), then Enter: ");
  try {
    return await reader.question("", { signal: controller.signal });
  } finally {
    reader.close();
    process.stdout.write("\n");
  }
}
function openBrowser(url) {
  if (process.platform === "darwin")
    return spawn("/usr/bin/open", [url], { stdio: "ignore", shell: false });
  if (process.platform === "win32")
    return spawn("rundll32", ["url.dll,FileProtocolHandler", url], {
      stdio: "ignore",
      shell: false,
    });
  return spawn("xdg-open", [url], { stdio: "ignore", shell: false });
}
function runBridge(client) {
  const path = resolve(ROOT, ".hej-hej/bridge.json");
  const prefs = existsSync(path) ? readConfig(path) : {};
  const owner = process.env.IMESSAGE_OWNER || prefs.owner,
    service = process.env.IMESSAGE_SERVICE_ID || prefs.service;
  if (!owner || !service)
    throw new Error(
      "Run npm run bridge:setup -- --owner YOUR-HANDLE --service YOUR-MESSAGES-SERVICE-ID first (or export IMESSAGE_OWNER and IMESSAGE_SERVICE_ID)",
    );
  const bridgeToken = process.env.BRIDGE_TOKEN || client.secrets.BRIDGE_TOKEN;
  if (!bridgeToken || bridgeToken.length < 32)
    throw new Error("No bridge credential found; run npm run setup");
  const env = {
    ASSISTANT_URL: client.url,
    BRIDGE_TOKEN: bridgeToken,
    IMESSAGE_OWNER: owner,
    IMESSAGE_SERVICE_ID: service,
  };
  // The Mac process gets only its own bearer, never admin/Gmail/Cloudflare credentials.
  for (const key of [
    "PATH",
    "HOME",
    "USER",
    "LOGNAME",
    "TMPDIR",
    "LANG",
    "LC_ALL",
    "__CF_USER_TEXT_ENCODING",
    "MESSAGES_DB",
    "BRIDGE_STATE_DIR",
  ])
    if (process.env[key]) env[key] = process.env[key];
  const child = spawn(process.execPath, [resolve(ROOT, "bridge/index.mjs")], {
    cwd: ROOT,
    env,
    stdio: "inherit",
  });
  child.on("exit", (code) => {
    process.exitCode = code ?? 1;
  });
  child.on("error", () => {
    console.error("Unable to launch Mac bridge");
    process.exitCode = 1;
  });
}
export async function main(command, args) {
  const local = args.includes("--local");
  args = args.filter((a) => a !== "--local");
  if (command === "setup") {
    const result = setup(ROOT, options(args, ["name", "email", "url"]));
    console.log(
      "Private setup saved in .hej-hej/; existing tokens preserved.\nNo credentials were printed or uploaded.\nNext: npm run login, then npm run deploy. Gmail and both channels are optional.",
    );
    if (result.config.vars.OWNER_EMAIL === "you@example.com")
      console.log(
        "Before connecting Gmail: npm run setup -- --email YOU@gmail.com",
      );
    return;
  }
  if (command === "secret") {
    const [key] = args;
    if (
      args.length !== 1 ||
      !SECRET_KEYS.has(key) ||
      ["ADMIN_TOKEN", "BRIDGE_TOKEN", "TOKEN_KEY"].includes(key)
    )
      throw new Error(
        "Choose one integration key from .env.example. Core keys are generated by setup, not rotated by this command.",
      );
    const path = resolve(ROOT, ".hej-hej/.dev.vars");
    if (!existsSync(path)) throw new Error("Run npm run setup first");
    const value = await hidden();
    if (!value || value.length > 8192 || /[\r\n\0]/.test(value))
      throw new Error("Invalid secret value");
    const secrets = readSecrets(path);
    secrets[key] = value;
    writeSecrets(path, secrets);
    console.log(key + " saved privately. Run npm run deploy to apply it.");
    return;
  }
  if (command === "login") {
    await wrangler(["login"]);
    return;
  }
  if (command === "deploy") {
    console.log(
      "Deploying to your Cloudflare account and uploading local secrets. Workers AI requests may incur usage charges.",
    );
    const url = await deploy();
    console.log(
      "Deployed: " +
        url +
        '\nNext: npm run doctor, then npm run ask -- "Hello"',
    );
    return;
  }
  if (command === "dev") {
    const managed = resolve(ROOT, ".hej-hej/wrangler.json");
    if (!existsSync(managed))
      throw new Error(
        "Run npm run setup first; use npm run demo for a no-account test",
      );
    await wrangler([
      "dev",
      "--config",
      managed,
      "--ip",
      "127.0.0.1",
      "--port",
      "8787",
    ]);
    return;
  }
  if (command === "bridge:setup") {
    const values = options(args, ["owner", "service"]);
    if (
      !values.owner ||
      !values.service ||
      /[\s\0]/.test(values.owner) ||
      /[\r\n\0]/.test(values.service)
    )
      throw new Error(
        "Specify a nonempty owner handle and dedicated Messages service ID",
      );
    if (!existsSync(resolve(ROOT, ".hej-hej/wrangler.json")))
      throw new Error("Run npm run setup first");
    privateWrite(
      resolve(ROOT, ".hej-hej/bridge.json"),
      JSON.stringify(values, null, 2) + "\n",
    );
    console.log(
      "Owner and Messages service saved privately. Next: npm run bridge. Full Disk Access and Messages Automation permission still need your approval.",
    );
    return;
  }
  if (command === "bridge:services") {
    if (process.platform !== "darwin")
      throw new Error("Messages services require macOS");
    const child = spawn(
      "/usr/bin/osascript",
      [
        "-e",
        'tell application "Messages" to get {id, name} of every service whose service type is iMessage',
      ],
      { stdio: "inherit", shell: false },
    );
    child.on("exit", (code) => {
      process.exitCode = code ?? 1;
    });
    return;
  }
  const client = configuration(ROOT, {
    local,
    requireAdmin: command !== "bridge",
  });
  if (command === "doctor") {
    console.log(
      "hej hej doctor — Node " +
        process.versions.node +
        ", " +
        process.platform,
    );
    const health = await api(client, "/health");
    if (health.product !== "hej hej")
      throw new Error("This endpoint is not hej hej; check ASSISTANT_URL");
    const status = await api(client, "/v1/status");
    console.log(
      "Backend: reachable; admin authentication works. Mode: " + health.mode,
    );
    console.log(
      "Gmail: " +
        (status.gmail
          ? "connected (readonly)"
          : "not connected — optional; add Google keys, deploy, then npm run connect:gmail"),
    );
    console.log(
      "Web: " +
        (status.web
          ? "key configured (not a live search test)"
          : "not configured — optional; add TAVILY_API_KEY and deploy"),
    );
    console.log(
      "WhatsApp: " +
        (status.whatsapp
          ? "keys configured (not a live delivery test)"
          : "not configured — optional; see WhatsApp setup"),
    );
    console.log(
      "iMessage: " +
        (process.platform === "darwin"
          ? "Mac available; bridge/permissions must be tested separately"
          : "needs a Mac; backend itself can run here"),
    );
    console.log(
      "Next: npm run smoke" +
        (local ? " -- --local" : "") +
        " (one greeting request; live mode uses Workers AI).",
    );
    return;
  }
  if (command === "ask") {
    const message = await ask(client, args.join(" "));
    console.log(message.response);
    return;
  }
  if (command === "smoke") {
    const result = await smoke(client);
    console.log(
      "PASS: auth, admission, durable reply and duplicate-ID handling (" +
        result.mode +
        ").\n" +
        result.response,
    );
    return;
  }
  if (command === "connect:gmail") {
    const result = await api(client, "/oauth/google/start", "POST", {});
    const url = new URL(result.url);
    if (url.protocol !== "https:" || url.hostname !== "accounts.google.com")
      throw new Error("Unexpected consent URL");
    console.log(
      "Opening Google readonly consent. Sign in as your configured owner. After approval, run npm run doctor.",
    );
    const browser = openBrowser(url.toString());
    browser.on("error", () =>
      console.log(
        "Browser couldn't open. Open this one-use consent URL privately:\n" +
          url.toString(),
      ),
    );
    browser.on("exit", (code) => {
      if (code)
        console.log(
          "Browser couldn't open. Open this one-use consent URL privately:\n" +
            url.toString(),
        );
    });
    return;
  }
  if (command === "bridge") {
    runBridge(client);
    return;
  }
  throw new Error("Unknown command");
}
if (
  process.argv[1] &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  main(process.argv[2], process.argv.slice(3)).catch((error) => {
    console.error(error.message);
    process.exitCode = 1;
  });
}
